# Generated by Django 3.0.7 on 2020-06-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateField(null=True),
        ),
    ]
